name: CI

on:
  workflow_dispatch:

  push:

  pull_request:
    branches:
      - master

jobs:
  count:
    runs-on: ubuntu-latest
    name: Count lines of code

    if: "!contains(github.event.head_commit.message,'forward:')"

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Count lines with CLoC
        run: |
          echo "::group:: Install CLoC"
          sudo apt-get install -y cloc
          echo "::endgroup::"
          cloc .

  test:
    runs-on: ubuntu-latest
    name: Testing
    needs: [count]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache poetry
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/cache
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install -vvv

      - name: Testing with pytest
        env:
          ENVIRONMENTS: ${{ secrets.DOTENV_FILE }}
        run: |
          export $ENVIRONMENTS
          touch configs/.env
          poetry run pytest

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: data/logs

  docker:
    runs-on: ubuntu-latest
    name: Build Docker Image
    needs: [count]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Add environment files
        env:
          ENVIRONMENTS: ${{ secrets.DOTENV_FILE }}
        run: |
          echo $ENVIRONMENTS > configs/.env

      - name: Test building Docker image
        run: |
          docker build .
