name: Lint

on:
  push:
    branches: [main, dev]

  pull_request_target:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install poetry
        run: pip install poetry

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - uses: suo/flake8-github-action@v1

      - uses: jakebailey/pyright-action@v1

  analyze:
    runs-on: ubuntu-latest
    name: CodeQL Analyze

    if: "!github.base_ref"

    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
