name: Lint

on:
  push:
    branches: [main, dev]

  pull_request_target:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pdm config python.use_venv false
          pdm export --group :all --dev \
            --format requirements --without-hashes \
            --output requirements.txt
          pip install -r requirements.txt

      - uses: suo/flake8-github-action@v1

      - uses: jakebailey/pyright-action@v1

  analyze:
    runs-on: ubuntu-latest
    name: CodeQL Analyze

    if: "!github.base_ref"

    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Auto build
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
