name: Generate Requirements.txt

on:
  workflow_dispatch:

  push:
    paths:
      - poetry.lock
      - pyproject.toml

jobs:
  generate:
    name: Generate Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Generate
        run: |
          pip install poetry
          poetry install
          poetry export -f requirements.txt -o requirements.txt --without-hashes

      - name: Push to repository
        run: |
          git config --global user.name github-action
          git config --global user.email noreply@github.com
          git add requirements.txt
          git commit -am ":pushpin: 更新requirements.txt"
          git push
